def big_list():
    return [
        "anduril", "mercury", "ramp", "replit", "notion", "persona", "scaleai",
        "humane", "runway", "varda", "lattice", "sandboxaq", "vanta", "linear",
        "pulumi", "datapane", "twoslash", "loftlabs", "orbit", "zest",
        "triplewhale", "maven", "tessellate", "replicate", "ponder", "zip",
        "sierra", "incidentio", "crescendo", "chord", "fervor", "concord",
        "patch", "openai", "superhuman", "attio", "arcjet", "zeno", "suade",
        "fellow", "particle", "luma", "tome", "highlight", "enso", "stepfun",
        "dust", "fig", "llamaindex", "cube", "truv", "jam", "superblocks",
        "posthog", "clearbit", "clockwork", "graphistry", "alphachain",
        "canopy", "sigmacomputing", "shipyard", "polar", "mitiga", "devrev",
        "airplane", "monogram", "sentry", "radix", "moment", "contenda",
        "bask", "laika", "chordx", "warmly", "paradime", "relay", "undo",
        "tarabut", "glyph", "front", "glidian", "numeral", "humanloop",
        "assemblyai", "deepgram", "lightdash", "loom", "bloop", "hex",
        "finch", "retain", "avalanche", "vector", "nira", "atomic", "sprig",
        "r2c", "delve", "dexai", "capchase", "skydio", "shapeways", "basho",
        "ribbon", "lumaai", "truveta", "bright", "tempo", "cerebras", "monad",
        "carbonhealth", "heat", "canvas", "layerzero", "sideline", "bolttech",
        "valence", "wildfire", "simplebet", "endor", "everlaw", "retainai",
        "armory", "radixlabs", "graviton", "whirlpool", "bluecore", "seafair",
        "envoy", "leeway", "project44", "instabase", "slice", "ridecell",
        "klara", "uplift", "ember", "shepherd", "twelve", "flexport", "polly",
        "viz", "corvus", "graviti", "zapata", "tenstorrent", "codesee",
        "basil", "raydiant", "openstore", "dutchie", "pave", "atrato",
        "ledger", "moov", "clear", "biorender", "amp", "protego", "omneky",
        "aurahealth", "lime", "brightseed", "id.me", "fisker", "rideco",
        "ambrook", "coast", "nava", "stytch", "modal", "writer", "peridio",
        "eternal", "zugata", "lev", "percepto", "moduscreate", "ribbonhealth",
        "onna", "canva", "mila", "smallstep", "relayfi", "phantombuster",
        "patronus", "emberfund", "loom", "triple", "primer", "convoy",
        "sundial", "retool", "arbington", "jetson", "plasma", "trove",
        "vastai", "verkada", "covertree", "parcl", "corelight", "splunk",
        "hightouch", "meld", "clair", "prisma", "runwayml", "plaid",
        "blackshark", "ocho", "safetywing", "rain", "simplist", "fonda",
        "clipboardhealth", "stedi", "brightwheel", "tend", "firstbase",
        "promise", "otto", "kern", "step", "crave", "soundhound", "wonder",
        "hitch", "carboncapture", "snickerdoodle", "athelas", "radar",
        "bluevision", "notionlabs", "fastgen", "auralabs", "retention",
        "dust.tt", "cohort", "faithful", "bearflagrobotics", "kalshi",
        "betterleap", "codacy", "gemini", "openinference", "monarch",
        "revops", "blend", "clave", "refinery", "mightyapp", "stream",
        "strobe", "volumetric", "zipline", "telos", "solvent", "turbine",
        "gravity", "poly", "arkestro", "conic", "signal", "metronome",
        "petal", "substack", "metaengine", "archipelago", "tomocube", "vayu",
        "lumenpay", "hydra", "strata", "rescale", "devoted", "invite", "eppo",
        "periscope", "xwing", "duckbill", "shape", "headway", "dignifi",
        "charm", "canopyservicing", "alchemy", "sequoia", "mystenlabs",
        "kumo", "uphold", "shadeform", "swim.ai", "shield", "goose",
        "ventura", "write", "loomai", "gravie", "deno", "uncover", "basis",
        "basisai", "figure", "neo", "specter", "brightflow", "pillow",
        "fluxon", "rivet", "operant", "observ", "vizion", "airkit", "finley",
        "convector", "signalwire", "squire", "postscript", "humana", "plus",
        "anchor", "sapling", "domain", "openphone", "brightmind", "altana",
        "zebrium", "fermat", "elementl", "bloom", "concordium", "lava",
        "ordway", "alchemyai", "wist", "arc", "gradient", "windfall",
        "paradox", "brightinsight", "opus", "verge", "inductive", "weka",
        "sora", "rodeo", "flare", "simplyinsured", "spice", "emulate",
        "altana", "pivot", "spree", "atom", "solugen", "recast", "slate",
        "ventureloop", "archimedes", "oryx", "aegis", "inference", "rival",
        "ravio", "assemble", "nearside", "datasaur", "trustlayer", "ai21",
        "saildrone", "stability", "vivid", "resin", "treatwell", "prism",
        "astroforge", "layr", "bask", "cadex", "phoenix", "keen", "sift",
        "latticeflow", "nineai", "verb", "twelvebio", "reduct", "rama",
        "cradle", "mindsdb", "incogni", "synq", "nobleai", "gemini-ai",
        "primer", "cortex", "relume", "argyle", "cadence", "butter", "monai",
        "render", "mozart", "paradox", "wekaio", "koala", "suno", "danti",
        "unify", "wasp", "totem", "grayscale", "aquila", "meridian",
        "groq", "protolabs", "trail", "shadeform", "ember", "basilica",
        "prismatic", "flume", "aurora", "fervo", "electricturtle", "wedge",
        "hume", "brightmoney", "voltaic", "soulmachines", "vay", "skydio",
        "canopylabs", "pingcap", "spin", "nebula", "lucid", "rheaply",
        "trala", "malcolm", "nightfall", "promptloop", "promptlayer",
        "decode", "andela", "honeycomb", "uptick", "torch", "edith", "aragon",
        "vizcom", "tabnine", "sight", "lightmatter", "whisper", "aetherbio",
        "beehiiv", "layers", "renumics", "tenstorrent", "wade", "peridot",
        "vibe", "observe", "inferex", "tonal", "arctype", "playbook",
        "truveta", "cedar", "bejamas", "loophealth", "foster", "scribe",
        "baseten", "solv", "kognitos", "polygon", "nook", "bluevision",
        "quora", "yhat", "fossa", "edithlabs", "peek", "nobleai", "relayfi",
        "ledger", "recursion", "crib", "laika", "plum", "sift", "pantheon",
        "mindful", "pave", "atrium", "vividly", "attune", "frontier",
        "multiply", "folia", "corteza", "ambient", "latchbio", "ocean",
        "relume", "dust", "mendel", "posthog", "echo", "hex", "quantify",
        "openinference", "parsec", "ironclad", "dig", "observ", "choosy",
        "perplexity", "everlaw", "empath", "brightseed", "forge", "coda",
        "brightly", "bloomtech", "crisp", "appsmith", "ready", "lightyear",
        "enclitic", "parchment", "front", "mogul", "openlayer", "promptloop",
        "vividly", "relume", "helix", "auralabs", "rewind", "ember", "specter",
        "cerbo"
    ]
